### ISSUE TITLE
th ebig gays

### ISSUE THREAD

**Issue by Alulululululu** [PurrPaws/MMORPG-IDC#1]
**Is your feature request related to a problem? Please describe.**
A clear and concise description ofmmmmmmwhat the problem is. Ex. I'm always frustrated when [...]
g
**Describe the solution gesrh
**Additional ggggg
![Capture](https://user-images.githubusercontent.com/26011615/64991060-6d002000-d8d1-11e9-82cc-5cabe579e97f.PNG)
**
s

**Comment by Alulululululu** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description ofmmmmmmwhat the problem is. Ex. I'm always frustrated when [...]
> g
> **Describe the solution gesrh
> **Additional ggggg
> ![Capture](https://user-images.githubusercontent.com/26011615/64991060-6d002000-d8d1-11e9-82cc-5cabe579e97f.PNG)
> **
> s

!yivgbftcrdxesw(z'qrx(tècdf§y!vgèuçhbinjào,ç)kàp;l^m:),ijàhnuçgb)yè!f§trd(s'ezqw"xrs(tècvyfguhbinjopk,^;l$m:$ù=

**Comment by MiauwWare** [comment]
This man is speaking the language of the gods.

**Comment by Alulululululu** [comment]
> This man is speaking the language of the gods.

no
